# Generated by Django 3.1.7 on 2021-03-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calorielist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('calories', models.TextField(default='', max_length=100)),
                ('fat', models.TextField(default='', max_length=100)),
                ('carbs', models.TextField(default='', max_length=100)),
                ('protein', models.TextField(default='', max_length=100)),
                ('sodium', models.TextField(default='', max_length=100)),
                ('calcium', models.TextField(default='', max_length=100)),
                ('iron', models.TextField(default='', max_length=100)),
                ('isType', models.TextField(default='', max_length=100)),
            ],
        ),
    ]
