# Generated by Django 3.1.7 on 2021-06-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('calories', models.IntegerField(default=0)),
                ('fat', models.TextField(default='', max_length=100)),
                ('carbs', models.TextField(default='', max_length=100)),
                ('protein', models.TextField(default='', max_length=100)),
                ('alternative', models.TextField(default='', max_length=100)),
                ('altkcal', models.TextField(default='', max_length=100)),
            ],
        ),
    ]
